### ISSUE TITLE
pneumatics subsystem and drivetrain gearbox shifter command

### ISSUE THREAD

**Issue by her0me** [Team-5509/PrincessZeta#13]

**Comment by Shalmezad** [comment]
You'll need to check with mechanical to see if they're going single relay or double relay (hopefully double...)

You'll also need to decide if you want it "while held shift low" or toggle shift. This will determine what your default command is, and how you tie it to OI (whileheld or whenpressed).

Make sure to make toggle high/low *instant* commands rather than the vanilla ones.

**Comment by her0me** [comment]
I will ask them about that I am sure they will go double if it's better for some reason. 

I am thinking toggle shift would be better right now.  I would say toggle to low gear and default high gear (which is fast, low power I think).

So, two separate commands?

**Comment by Shalmezad** [comment]
Yep, 2 separate (instant) commands, tied to 2 separate buttons, no default set on the subsystem (so it won't go "back" when the command finishes). 

You'll want to make sure all your autons have "shift high" as the first command for consistency, and to ensure you start in the right gear.
